username: pranavc1515@gmail.com
password: Metapercept#2016
phone_number: 8805047968

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Full stack developer


locations:
- Michigan
- Remote

salary: 70,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: D:\AutomationScript\pranav-resume.pdf
  Cover Letter: D:\AutomationScript\pranav-resume.pdf
  #Photo: # PATH TO photo


output_filename:
- D:\AutomationScript\out.csv

# blacklist:
#   - 'metapercept technology services'
#   - 'avathi ventures private limited'
# - # Company names you want to ignore

experience_level:
  # - 1 # Entry level
  # - 2 # Associate
  # - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship